### ISSUE TITLE
[PE-D][Tester A] Create command error message typo

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-4/tp#170]
The error message for the `create` command does not give a valid command.

![Screenshot 2023-11-03 at 4.55.45 PM.png](https://raw.githubusercontent.com/Elijah5399/ped/main/files/8dc6b76d-dfea-4eca-b9ba-ea54b1e5b04b.png)

If I copy-paste this `create` command, it gives an error as the telegram contact does not start with @.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Elijah5399/ped#6

**Comment by KamiliArsyad** [comment]
I don't understand the issue and I cannot reproduce it:
![image](https://github.com/AY2324S1-CS2103T-F11-4/tp/assets/22293969/0ecd2f57-9479-4f9b-a826-e2fdcabb68fe)

**Comment by zhyuhan** [comment]
Seems to be an issue with the example in the error message, `telegram` is missing an `@`.
