### ISSUE TITLE
[PE-D][Tester C] Invalid profession can be added and edited to a client profile

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-4/tp#172]
When editing the client profile, I can change the profession to some numbers like 123 which is an invalid profession but it can still be updated successfully as shown in the screenshot below.

![image.png](https://raw.githubusercontent.com/Jweng88/ped/main/files/f21bafda-f489-465a-bcb3-14b6f3f8f917.png)

Perhaps can add restrictions in the profession parameter to check for invalid inputs like numbers or symbols?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Jweng88/ped#8

**Comment by KamiliArsyad** [comment]
Connectify would like the profession field to stay flexible. One might use some cryptic way that he would like to remember a person's profession is, and we would never know.
TODO: Add documentation.
