### ISSUE TITLE
[PE-D][Tester C] Multiple optional income parameters can be added into a client profile

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-4/tp#174]
Although the UserGuide states that multiple optional parameters are allowed, so that I can input multiple incomes to the client successfully as shown in the screenshot below, it does not make sense for a client to have multiple incomes. 

![image.png](https://raw.githubusercontent.com/Jweng88/ped/main/files/542d0c73-4eb6-4362-9689-dec449b3a47a.png)

Perhaps you can refer to your edit feature that does check for single-valued fields like income field and use it for the create feature so that only one income field can be added for each client optionally?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Jweng88/ped#9

**Comment by KamiliArsyad** [comment]
This will actually broke the entire app idk why so imma tag everyone @zhyuhan @lilozz2 @dickongwd @MagnificentCreature

**Comment by lilozz2** [comment]
Ran this on my end and app does not seem to crash, not sure about the rest @zhyuhan @dickongwd @MagnificentCreature

**Comment by zhyuhan** [comment]
Works fine on the latest version.
