### ISSUE TITLE
[PE-D][Tester C] Unable to delete created tag for a client profile

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-4/tp#176]
In the UserGuide, there were only mentions of deleting a client, but no mentions of deleting created tags. In the event of a user accidentally creating tags or lead, the user is unable to undo the action as the only way currently is to manually edit the `addressbook.json` file. Perhaps can consider providing users a way to remove unwanted tags or lead from a client profile?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Jweng88/ped#11

**Comment by dickongwd** [comment]
Update user guide to show how to delete tag using `edit INDEX t/`.
