### ISSUE TITLE
Schedule updated UI has minor visual bug

### ISSUE THREAD

**Issue by MagnificentCreature** [AY2324S1-CS2103T-F11-4/tp#219]
A follow-up list might be compressed into "..." just click on it to fix the minor bug.

Edit: I do not believe we have time to fix this in v1.4

https://github.com/AY2324S1-CS2103T-F11-4/tp/assets/61371541/6d2cf3d8-1c52-451a-8ddf-d68e477583ee

**Comment by zhyuhan** [comment]
Yup, we won't have time to fix this.
