### ISSUE TITLE
Add functionality for interactions

### ISSUE THREAD

**Issue by dickongwd** [AY2324S1-CS2103T-F11-4/tp#37]
Currently we are able to create interactions and tag it to each client, but we are missing a few key functionalities.

We need to be able to:
- view interactions for each client (need to consider how we can design this)
- be able to edit interactions
- delete interactions if needed

**Comment by lilozz2** [comment]
Would be good to add a date field to each interaction as well

**Comment by zhyuhan** [comment]
> view interactions for each client (need to consider how we can design this)

The ability to view interactions has been added in #44.
