### ISSUE TITLE
As a salesperson, I can set follow-up frequency for each client category, so I know how often to reach out.

### ISSUE THREAD

**Issue by dickongwd** [AY2324S1-CS2103T-F11-4/tp#56]
New command?

Either it is implemented by
1. Setting a follow-up frequency (by Lead), and the follow-up meeting is automatically determined from the last meeting date, or
2. The follow-up meeting date is manually set by the user

**Comment by lilozz2** [comment]
Default Lead timings
- Cold: 8 Weeks
- Warm: 4 Weeks
- Hot: 1 Week
