### ISSUE TITLE
Interaction command not parsing date

### ISSUE THREAD

**Issue by lilozz2** [AY2324S1-CS2103T-F11-4/tp#77]
Interaction class supports the adding of date field but the actual command is not parsing the date yet

**Comment by MagnificentCreature** [comment]
Didn't we agree it doesn't need to parse the date? It uses the current system time

**Comment by MagnificentCreature** [comment]
If its for the sake of the Json parsing, I'll handle it separately. It shouldn’t be in the interaction command in that case, but the Json reader.
